spring:
  application:
    name: LobbyApi
  data:
    mongodb:
      uri: mongodb+srv://papaletagg67:Xagohdji02QK7ub8@clustertamal.mcsgqhm.mongodb.net/basearsw?retryWrites=true&w=majority&appName=ClusterTamal
      database: basearsw


